version: '3.8'
services:
  react-app:
    container_name: react-app
    build: 
      context: ./manage-worker_react/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: aspnetcore-api
    build: 
      context: ./ManageWorker_API/
      dockerfile: Dockerfile
    ports:
      - 5177:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
