// <auto-generated />
using System;
using ManageWorker_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageWorker_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231227073222_initStuffTable")]
    partial class initStuffTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ManageWorker_API.Models.Stuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stuff");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Stuff");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ManageWorker_API.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StuffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StuffId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("ManageWorker_API.Models.Dto.StuffDTO", b =>
                {
                    b.HasBaseType("ManageWorker_API.Models.Stuff");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("StuffDTO");
                });

            modelBuilder.Entity("ManageWorker_API.Models.Worker", b =>
                {
                    b.HasOne("ManageWorker_API.Models.Stuff", "Stuff")
                        .WithMany("WorkerList")
                        .HasForeignKey("StuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stuff");
                });

            modelBuilder.Entity("ManageWorker_API.Models.Stuff", b =>
                {
                    b.Navigation("WorkerList");
                });
#pragma warning restore 612, 618
        }
    }
}
